Repository linkcollect/Main-Website-Linkcollect, pull requests merged in 2023-10, with the labels that each got.

#164 Sitemap + Bu Fix Invalid Credentials
  public/sitemap.xml
  src/pages/Login.jsx
Labels: hacktoberfest-accepted

#172 Update ProfileHeader.jsx
  src/components/Sections/Home/ProfileHeader.jsx
Labels: hacktoberfest-accepted

#169 Fixes Invalid Password message on first visit
  src/pages/Signup.jsx
Labels: under review

#154 Google analytics
  package-lock.json
  package.json
  public/index.html
  src/App.js
  src/components/Layout/Navbar/Navabar.jsx
  src/components/Sections/LandingPageV2/Main.jsx
  src/components/Sections/LandingPageV2/Navbar.jsx
  src/components/analytics/gaAnalyticsEventHandler.js
  src/hooks/useAnalyticsEventTracker.jsx
  src/index.js
  src/pages/LandingPageV2.jsx
  src/pages/Login.jsx
Labels: hacktoberfest-accepted

#185 Z index fix
  src/components/Common/ActiondropDown.jsx
  src/components/Sections/Bookmarks/BookmarkItemGrid.jsx
  src/pages/Bookmarks.jsx
Labels: hacktoberfest-accepted

#196 fixed dark mode issues
  src/assets/GridView.svg
  src/assets/darkMode/darkmodeGridView.svg
  src/components/Common/ActiondropDown.jsx
  src/pages/SavedCollection.jsx
Labels: hacktoberfest-accepted

#197 Added social link validation check
  src/components/Sections/Settings/Profile.jsx
Labels: hacktoberfest-accepted

#206 text overflow issue fixed
  src/components/UI/BackgroundGraident/BackgroundGradient.jsx
Labels: hacktoberfest-accepted

#216 fix: crash when clicking unimplemented feature
  src/pages/SavedCollection.jsx
Labels: hacktoberfest, hacktoberfest-accepted

#218 Fixed text overlap issue, added upload image checks
  src/components/Sections/Settings/Profile.jsx
Labels: hacktoberfest, hacktoberfest-accepted
